# Generated by Django 5.1.4 on 2025-01-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0004_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='status_courier',
        ),
    ]
